display_name: NodeUnion

packager: jichanglianmeng
packagerEmail: support@jichanglianmeng.app
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - NodeUnion
  - Clash
  - ClashMeta
  - Proxy

generic_name: NodeUnion

group: Applications/Internet

startup_notify: true
