display_name: NodeUnion

icon: ./assets/images/icon.png

keywords:
  - NodeUnion
  - Clash
  - ClashMeta
  - Proxy

generic_name: NodeUnion

categories:
  - Network

startup_notify: true

include: []
