// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6zs-pX-K5KD_Rza2Xu5DV4SA7FHtO_E',
    appId: '1:1056380482639:android:7b4d79b4ea4f0cc05aa63a',
    messagingSenderId: '1056380482639',
    projectId: 'jichanglianmeng',
    storageBucket: 'jichanglianmeng.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbsFj8zQrjfMWXWax5IF5YHgV-sSQaB7M',
    appId: '1:1056380482639:ios:ebd1e9ad47092d245aa63a',
    messagingSenderId: '1056380482639',
    projectId: 'jichanglianmeng',
    storageBucket: 'jichanglianmeng.firebasestorage.app',
    iosBundleId: 'com.jichanglianmeng.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg43Ei_MPrKbfO9GR8lcAoXlO0_YkmoiE',
    appId: '1:1056380482639:web:1621ba893431ef4a5aa63a',
    messagingSenderId: '1056380482639',
    projectId: 'jichanglianmeng',
    authDomain: 'jichanglianmeng.firebaseapp.com',
    storageBucket: 'jichanglianmeng.firebasestorage.app',
  );

}