display_name: NodeUnion
package_name: jichanglianmeng
maintainer:
  name: jichanglianmeng
  email: support@jichanglianmeng.app

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - NodeUnion
  - Clash
  - ClashMeta
  - Proxy

generic_name: NodeUnion

categories:
  - Network

startup_notify: true
